@echo off
cd /d %arma2oapath%
for %%f in (
Expansion\Addons\air_e.pbo
Expansion\Addons\air_e.pbo.bi.bisign
Expansion\Addons\air_e.pbo.bi2.bisign
Expansion\Addons\animals_e.pbo
Expansion\Addons\animals_e.pbo.bi.bisign
Expansion\Addons\animals_e.pbo.bi2.bisign
Expansion\Addons\anims_e.pbo
Expansion\Addons\anims_e.pbo.bi.bisign
Expansion\Addons\anims_e.pbo.bi2.bisign
Expansion\Addons\ca_e.pbo
Expansion\Addons\ca_e.pbo.bi.bisign
Expansion\Addons\ca_e.pbo.bi2.bisign
Expansion\Addons\characters_e.pbo
Expansion\Addons\characters_e.pbo.bi.bisign
Expansion\Addons\characters_e.pbo.bi2.bisign
Expansion\Addons\desert_e.pbo
Expansion\Addons\desert_e.pbo.bi.bisign
Expansion\Addons\desert_e.pbo.bi2.bisign
Expansion\Addons\dubbingradio_e.pbo
Expansion\Addons\dubbingradio_e.pbo.bi.bisign
Expansion\Addons\dubbingradio_e.pbo.bi2.bisign
Expansion\Addons\dubbing_e.pbo
Expansion\Addons\dubbing_e.pbo.bi.bisign
Expansion\Addons\dubbing_e.pbo.bi2.bisign
Expansion\Addons\l39.pbo
Expansion\Addons\l39.pbo.bi.bisign
Expansion\Addons\l39.pbo.bi2.bisign
Expansion\Addons\language.pbo
Expansion\Addons\language.pbo.bi.bisign
Expansion\Addons\language.pbo.bi2.bisign
Expansion\Addons\languagemissions.pbo
Expansion\Addons\languagemissions.pbo.bi.bisign
Expansion\Addons\languagemissions.pbo.bi2.bisign
Expansion\Addons\languagemissions_e.pbo
Expansion\Addons\languagemissions_e.pbo.bi.bisign
Expansion\Addons\languagemissions_e.pbo.bi2.bisign
Expansion\Addons\language_e.pbo
Expansion\Addons\language_e.pbo.bi.bisign
Expansion\Addons\language_e.pbo.bi2.bisign
Expansion\Addons\misc_e.pbo
Expansion\Addons\misc_e.pbo.bi.bisign
Expansion\Addons\misc_e.pbo.bi2.bisign
Expansion\Addons\missions_e.pbo
Expansion\Addons\missions_e.pbo.bi.bisign
Expansion\Addons\missions_e.pbo.bi2.bisign
Expansion\Addons\modules_e.pbo
Expansion\Addons\modules_e.pbo.bi.bisign
Expansion\Addons\modules_e.pbo.bi2.bisign
Expansion\Addons\mp_armory.pbo
Expansion\Addons\mp_armory.pbo.bi.bisign
Expansion\Addons\mp_armory.pbo.bi2.bisign
Expansion\Addons\music_e.pbo
Expansion\Addons\music_e.pbo.bi.bisign
Expansion\Addons\music_e.pbo.bi2.bisign
Expansion\Addons\plants_e.pbo
Expansion\Addons\plants_e.pbo.bi.bisign
Expansion\Addons\plants_e.pbo.bi2.bisign
Expansion\Addons\roads_e.pbo
Expansion\Addons\roads_e.pbo.bi.bisign
Expansion\Addons\roads_e.pbo.bi2.bisign
Expansion\Addons\rocks_e.pbo
Expansion\Addons\rocks_e.pbo.bi.bisign
Expansion\Addons\rocks_e.pbo.bi2.bisign
Expansion\Addons\signs_e.pbo
Expansion\Addons\signs_e.pbo.bi.bisign
Expansion\Addons\signs_e.pbo.bi2.bisign
Expansion\Addons\soundmissions_e.pbo
Expansion\Addons\soundmissions_e.pbo.bi.bisign
Expansion\Addons\soundmissions_e.pbo.bi2.bisign
Expansion\Addons\sounds_e.pbo
Expansion\Addons\sounds_e.pbo.bi.bisign
Expansion\Addons\sounds_e.pbo.bi2.bisign
Expansion\Addons\structures_e.pbo
Expansion\Addons\structures_e.pbo.bi.bisign
Expansion\Addons\structures_e.pbo.bi2.bisign
Expansion\Addons\takistan.pbo
Expansion\Addons\takistan.pbo.bi.bisign
Expansion\Addons\takistan.pbo.bi2.bisign
Expansion\Addons\takistan_data.pbo
Expansion\Addons\takistan_data.pbo.bi.bisign
Expansion\Addons\takistan_data.pbo.bi2.bisign
Expansion\Addons\takistan_data_layers.pbo
Expansion\Addons\takistan_data_layers.pbo.bi.bisign
Expansion\Addons\takistan_data_layers.pbo.bi2.bisign
Expansion\Addons\tracked_e.pbo
Expansion\Addons\tracked_e.pbo.bi.bisign
Expansion\Addons\tracked_e.pbo.bi2.bisign
Expansion\Addons\ui.pbo
Expansion\Addons\ui.pbo.bi.bisign
Expansion\Addons\ui.pbo.bi2.bisign
Expansion\Addons\warfare2.pbo
Expansion\Addons\warfare2.pbo.bi.bisign
Expansion\Addons\warfare2.pbo.bi2.bisign
Expansion\Addons\warfare2_e.pbo
Expansion\Addons\warfare2_e.pbo.bi.bisign
Expansion\Addons\warfare2_e.pbo.bi2.bisign
Expansion\Addons\weapons_e.pbo
Expansion\Addons\weapons_e.pbo.bi.bisign
Expansion\Addons\weapons_e.pbo.bi2.bisign
Expansion\Addons\wheeled_e.pbo
Expansion\Addons\wheeled_e.pbo.bi.bisign
Expansion\Addons\wheeled_e.pbo.bi2.bisign
Expansion\Addons\zargabad.pbo
Expansion\Addons\zargabad.pbo.bi.bisign
Expansion\Addons\zargabad.pbo.bi2.bisign
) do %md5% %%f >> "%workingpath%\arma2oamd5check.txt"
exit