@echo off
for %%f in (
Addons\a10.pbo
Addons\a10.pbo.bi.bisign
Addons\a10.pbo.bi2.bisign
Addons\ah64.pbo
Addons\ah64.pbo.bi.bisign
Addons\ah64.pbo.bi2.bisign
Addons\air.pbo
Addons\air.pbo.bi.bisign
Addons\air.pbo.bi2.bisign
Addons\air2.pbo
Addons\air2.pbo.bi.bisign
Addons\air2.pbo.bi2.bisign
Addons\Air3.pbo
Addons\Air3.pbo.bi.bisign
Addons\air3.pbo.bi2.bisign
Addons\animals.pbo
Addons\animals.pbo.bi.bisign
Addons\animals.pbo.bi2.bisign
Addons\animals2.pbo
Addons\animals2.pbo.bi.bisign
Addons\animals2.pbo.bi2.bisign
Addons\anims.pbo
Addons\anims.pbo.bi.bisign
Addons\anims.pbo.bi2.bisign
Addons\buildings.pbo
Addons\buildings.pbo.bi.bisign
Addons\buildings.pbo.bi2.bisign
Addons\buildings2.pbo
Addons\buildings2.pbo.bi.bisign
Addons\buildings2.pbo.bi2.bisign
Addons\buildings2_Ind_CementWorks.pbo
Addons\buildings2_Ind_CementWorks.pbo.bi.bisign
Addons\buildings2_ind_cementworks.pbo.bi2.bisign
Addons\Ca.pbo
Addons\Ca.pbo.bi.bisign
Addons\ca.pbo.bi2.bisign
Addons\characters.pbo
Addons\characters.pbo.bi.bisign
Addons\characters.pbo.bi2.bisign
Addons\characters2.pbo
Addons\characters2.pbo.bi.bisign
Addons\characters2.pbo.bi2.bisign
Addons\chernarus.pbo
Addons\chernarus.pbo.bi.bisign
Addons\chernarus.pbo.bi2.bisign
Addons\chernarus_Data.pbo
Addons\chernarus_Data.pbo.bi.bisign
Addons\chernarus_data.pbo.bi2.bisign
Addons\chernarus_Data_Layers.pbo
Addons\chernarus_Data_Layers.pbo.bi.bisign
Addons\chernarus_data_layers.pbo.bi2.bisign
Addons\dubbing.pbo
Addons\dubbing.pbo.bi.bisign
Addons\dubbing.pbo.bi2.bisign
Addons\editor.pbo
Addons\editor.pbo.bi.bisign
Addons\editor.pbo.bi2.bisign
Addons\language.pbo
Addons\language.pbo.bi.bisign
Addons\language.pbo.bi2.bisign
Addons\languagemissions.pbo
Addons\languagemissions.pbo.bi.bisign
Addons\languagemissions.pbo.bi2.bisign
Addons\misc.pbo
Addons\misc.pbo.bi.bisign
Addons\misc.pbo.bi2.bisign
Addons\misc2.pbo
Addons\misc2.pbo.bi.bisign
Addons\misc2.pbo.bi2.bisign
Addons\misc3.pbo
Addons\misc3.pbo.bi.bisign
Addons\misc3.pbo.bi2.bisign
Addons\misc_fix.pbo
Addons\misc_fix.pbo.bi.bisign
Addons\misc_fix.pbo.bi2.bisign
Addons\missions.pbo
Addons\missions.pbo.bi.bisign
Addons\missions.pbo.bi2.bisign
Addons\missions_ew.pbo
Addons\missions_ew.pbo.bi.bisign
Addons\missions_ew.pbo.bi2.bisign
Addons\modules.pbo
Addons\modules.pbo.bi.bisign
Addons\modules.pbo.bi2.bisign
Addons\music.pbo
Addons\music.pbo.bi.bisign
Addons\music.pbo.bi2.bisign
Addons\plants2_Bush.pbo
Addons\plants2_Bush.pbo.bi.bisign
Addons\plants2_bush.pbo.bi2.bisign
Addons\plants2_Clutter.pbo
Addons\plants2_Clutter.pbo.bi.bisign
Addons\plants2_clutter.pbo.bi2.bisign
Addons\plants2_misc.pbo
Addons\plants2_misc.pbo.bi.bisign
Addons\plants2_misc.pbo.bi2.bisign
Addons\plants2_Plant.pbo
Addons\plants2_Plant.pbo.bi.bisign
Addons\plants2_plant.pbo.bi2.bisign
Addons\plants2_Tree.pbo
Addons\plants2_Tree.pbo.bi.bisign
Addons\plants2_tree.pbo.bi2.bisign
Addons\Roads2.pbo
Addons\Roads2.pbo.bi.bisign
Addons\roads2.pbo.bi2.bisign
Addons\rocks2.pbo
Addons\rocks2.pbo.bi.bisign
Addons\rocks2.pbo.bi2.bisign
Addons\signs2.pbo
Addons\signs2.pbo.bi.bisign
Addons\signs2.pbo.bi2.bisign
Addons\soundmissions.pbo
Addons\soundmissions.pbo.bi.bisign
Addons\soundmissions.pbo.bi2.bisign
Addons\sounds.pbo
Addons\sounds.pbo.bi.bisign
Addons\sounds.pbo.bi2.bisign
Addons\structures.pbo
Addons\structures.pbo.bi.bisign
Addons\structures.pbo.bi2.bisign
Addons\tracked.pbo
Addons\tracked.pbo.bi.bisign
Addons\tracked.pbo.bi2.bisign
Addons\tracked2.pbo
Addons\tracked2.pbo.bi.bisign
Addons\tracked2.pbo.bi2.bisign
Addons\ui.pbo
Addons\ui.pbo.bi.bisign
Addons\ui.pbo.bi2.bisign
Addons\UIFonts.pbo
Addons\UIFonts.pbo.bi.bisign
Addons\uifonts.pbo.bi2.bisign
Addons\utes.pbo
Addons\utes.pbo.bi.bisign
Addons\utes.pbo.bi2.bisign
Addons\warfare2.pbo
Addons\warfare2.pbo.bi.bisign
Addons\warfare2.pbo.bi2.bisign
Addons\warfare2vehicles.pbo
Addons\warfare2vehicles.pbo.bi.bisign
Addons\warfare2vehicles.pbo.bi2.bisign
Addons\water.pbo
Addons\water.pbo.bi.bisign
Addons\water.pbo.bi2.bisign
Addons\water2.pbo
Addons\water2.pbo.bi.bisign
Addons\water2.pbo.bi2.bisign
Addons\weapons.pbo
Addons\weapons.pbo.bi.bisign
Addons\weapons.pbo.bi2.bisign
Addons\weapons2.pbo
Addons\weapons2.pbo.bi.bisign
Addons\weapons2.pbo.bi2.bisign
Addons\wheeled.pbo
Addons\wheeled.pbo.bi.bisign
Addons\wheeled.pbo.bi2.bisign
Addons\wheeled2.pbo
Addons\wheeled2.pbo.bi.bisign
Addons\wheeled2.pbo.bi2.bisign
Addons\wheeled3.pbo
Addons\wheeled3.pbo.bi.bisign
Addons\wheeled3.pbo.bi2.bisign
) do echo %%f: size - %%~zf >> "%workingpath%\arma2sizecheck.txt"
exit