@echo off
cd /d %arma2oapath%
for %%f in (
@KrayZ\mod.cpp
@KrayZ\mod.paa
@KrayZ\Addons\ASC_EU_Lights.pbo
@KrayZ\Addons\ASC_EU_Lights.pbo.krayz.bisign
@KrayZ\Addons\dayz.pbo
@KrayZ\Addons\dayz.pbo.dayz.bisign
@KrayZ\Addons\dayz_anim.pbo
@KrayZ\Addons\dayz_anim.pbo.krayz.bisign
@KrayZ\Addons\dayz_code.pbo
@KrayZ\Addons\dayz_code.pbo.krayz.bisign
@KrayZ\Addons\dayz_communityassets.pbo
@KrayZ\Addons\dayz_communityassets.pbo.dayz.bisign
@KrayZ\Addons\dayz_equip.pbo
@KrayZ\Addons\dayz_equip.pbo.dayz.bisign
@KrayZ\Addons\dayz_krayz.pbo
@KrayZ\Addons\dayz_krayz.pbo.krayz.bisign
@KrayZ\Addons\dayz_sfx.pbo
@KrayZ\Addons\dayz_sfx.pbo.krayz.bisign
@KrayZ\Addons\dayz_vehicles.pbo
@KrayZ\Addons\dayz_vehicles.pbo.dayz.bisign
@KrayZ\Addons\dayz_weapons.pbo
@KrayZ\Addons\dayz_weapons.pbo.dayz.bisign
@KrayZ\Addons\ksk_mod.pbo
@KrayZ\Addons\ksk_mod.pbo.krayz.bisign
@KrayZ\Addons\r3f_armes.pbo
@KrayZ\Addons\r3f_armes.pbo.R3F.bisign
@KrayZ\Addons\SBE_SOTG.pbo
@KrayZ\Addons\SBE_SOTG.pbo.krayz.bisign
@KrayZ\Addons\smk_anims.pbo
@KrayZ\Addons\smk_anims.pbo.krayz.bisign
@KRAYZ_CBA+JSRS\license.txt
@KRAYZ_CBA+JSRS\mod.cpp
@KRAYZ_CBA+JSRS\readme.txt
@KRAYZ_CBA+JSRS\addons\cba_a2_main.pbo
@KRAYZ_CBA+JSRS\addons\cba_a2_main.pbo.cba_a2_b8.bisign
@KRAYZ_CBA+JSRS\addons\cba_a2_xeh.pbo
@KRAYZ_CBA+JSRS\addons\cba_a2_xeh.pbo.cba_a2_b8.bisign
@KRAYZ_CBA+JSRS\addons\cba_ai.pbo
@KRAYZ_CBA+JSRS\addons\cba_ai.pbo.cba_b179.bisign
@KRAYZ_CBA+JSRS\addons\cba_arrays.pbo
@KRAYZ_CBA+JSRS\addons\cba_arrays.pbo.cba_b179.bisign
@KRAYZ_CBA+JSRS\addons\cba_common.pbo
@KRAYZ_CBA+JSRS\addons\cba_common.pbo.cba_b179.bisign
@KRAYZ_CBA+JSRS\addons\cba_diagnostic.pbo
@KRAYZ_CBA+JSRS\addons\cba_diagnostic.pbo.cba_b179.bisign
@KRAYZ_CBA+JSRS\addons\cba_events.pbo
@KRAYZ_CBA+JSRS\addons\cba_events.pbo.cba_b179.bisign
@KRAYZ_CBA+JSRS\addons\cba_extended_eventhandlers.pbo
@KRAYZ_CBA+JSRS\addons\cba_extended_eventhandlers.pbo.cba_b179.bisign
@KRAYZ_CBA+JSRS\addons\cba_hashes.pbo
@KRAYZ_CBA+JSRS\addons\cba_hashes.pbo.cba_b179.bisign
@KRAYZ_CBA+JSRS\addons\cba_help.pbo
@KRAYZ_CBA+JSRS\addons\cba_help.pbo.cba_b179.bisign
@KRAYZ_CBA+JSRS\addons\cba_main.pbo
@KRAYZ_CBA+JSRS\addons\cba_main.pbo.cba_b179.bisign
@KRAYZ_CBA+JSRS\addons\cba_network.pbo
@KRAYZ_CBA+JSRS\addons\cba_network.pbo.cba_b179.bisign
@KRAYZ_CBA+JSRS\addons\cba_oa_main.pbo
@KRAYZ_CBA+JSRS\addons\cba_oa_main.pbo.cba_oa_b6.bisign
@KRAYZ_CBA+JSRS\addons\cba_oa_xeh.pbo
@KRAYZ_CBA+JSRS\addons\cba_oa_xeh.pbo.cba_oa_b6.bisign
@KRAYZ_CBA+JSRS\addons\cba_strings.pbo
@KRAYZ_CBA+JSRS\addons\cba_strings.pbo.cba_b179.bisign
@KRAYZ_CBA+JSRS\addons\cba_ui.pbo
@KRAYZ_CBA+JSRS\addons\cba_ui.pbo.cba_b179.bisign
@KRAYZ_CBA+JSRS\addons\cba_ui_helper.pbo
@KRAYZ_CBA+JSRS\addons\cba_ui_helper.pbo.cba_oa_b6.bisign
@KRAYZ_CBA+JSRS\addons\cba_ui_helper_a2.pbo
@KRAYZ_CBA+JSRS\addons\cba_ui_helper_a2.pbo.cba_a2_b8.bisign
@KRAYZ_CBA+JSRS\addons\cba_vectors.pbo
@KRAYZ_CBA+JSRS\addons\cba_vectors.pbo.cba_b179.bisign
@KRAYZ_CBA+JSRS\addons\cba_versioning.pbo
@KRAYZ_CBA+JSRS\addons\cba_versioning.pbo.cba_b179.bisign
@KRAYZ_CBA+JSRS\addons\cba_xeh.pbo
@KRAYZ_CBA+JSRS\addons\cba_xeh.pbo.cba_b179.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_ah64.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_ah64.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_ah64_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_ah64_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_ak107.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_ak107.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_ak107_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_ak107_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_ak47.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_ak47.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_ak47_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_ak47_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_ak74.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_ak74.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_ak74gl.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_ak74gl.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_ak74gl_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_ak74gl_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_ak74_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_ak74_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_akm.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_akm.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_akm_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_akm_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_aks74.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_aks74.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_aks74u.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_aks74u.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_aks74un.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_aks74un.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_aks74un_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_aks74un_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_aks74u_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_aks74u_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_aks74_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_aks74_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_as50.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_as50.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_as50_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_as50_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_atv.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_atv.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_atv_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_atv_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_bizon.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_bizon.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_bizonsd.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_bizonsd.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_bizonsd_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_bizonsd_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_bizon_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_bizon_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_bullethits.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_bullethits.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_bullethits_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_bullethits_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_ch47.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_ch47.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_ch47_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_ch47_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_cz550.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_cz550.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_cz550_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_cz550_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_distance.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_distance.pbo.krayz.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_distance_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_distance_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_dmr.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_dmr.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_dmr_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_dmr_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_explosions.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_explosions.pbo.krayz.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_explosions_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_explosions_c.pbo.krayz.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_famas_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_famas_c.pbo.krayz.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_flares.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_flares.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_flare_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_flare_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_fnfal.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_fnfal.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_fnfal_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_fnfal_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_frf2_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_frf2_c.pbo.krayz.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_g36a.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_g36a.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_g36a_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_g36a_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_g36c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_g36c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_g36c_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_g36c_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_g36k.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_g36k.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_g36k_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_g36k_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_g36mg.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_g36mg.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_g36mg_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_g36mg_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_g36sd.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_g36sd.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_g36sd_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_g36sd_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_glock17.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_glock17.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_glock17_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_glock17_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_hk417.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_hk417.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_hk417_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_hk417_c.pbo.krayz.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_humvee.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_humvee.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_humvee_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_humvee_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_l85a2.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_l85a2.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_l85a2_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_l85a2_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_l86a2.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_l86a2.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_l86a2_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_l86a2_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_leeenfield.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_leeenfield.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_leeenfield_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_leeenfield_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m107.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m107.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m107_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m107_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m14.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m14.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m14_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m14_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m16.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m16.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m16_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m16_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m1911.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m1911.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m1911_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m1911_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m203.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m203.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m203_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m203_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m24.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m24.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m240.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m240.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m240coax.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m240coax.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m240coax_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m240coax_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m240_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m240_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m24_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m24_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m40.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m40.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m40_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m40_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m4a1.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m4a1.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m4a1_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m4a1_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m4a3.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m4a3.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m4a3_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m4a3_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m4aim.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m4aim.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m4aim_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m4aim_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m4rco.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m4rco.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m4rco_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m4rco_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m4sd.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m4sd.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m4sd_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m4sd_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m9.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m9.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m9sd.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m9sd.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m9sd_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m9sd_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_m9_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_m9_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_mi17.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_mi17.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_mi17_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_mi17_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_mk48.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_mk48.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_mk48_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_mk48_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_mmt.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_mmt.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_mmt_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_mmt_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_mp5.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_mp5.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_mp5sd.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_mp5sd.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_mp5sd_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_mp5sd_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_mp5_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_mp5_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_mtvr.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_mtvr.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_mtvr_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_mtvr_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_pgm_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_pgm_c.pbo.krayz.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_radio_chatter.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_radio_chatter.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_radio_chatter_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_radio_chatter_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_revolver.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_revolver.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_revolver_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_revolver_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_rpk.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_rpk.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_rpk_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_rpk_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_sa58.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_sa58.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_sa58_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_sa58_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_sa61.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_sa61.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_sa61_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_sa61_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_scar_h.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_scar_h.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_scar_h_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_scar_h_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_scar_l.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_scar_l.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_scar_l_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_scar_l_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_suv.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_suv.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_suv_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_suv_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_svd.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_svd.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_svdcamo.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_svdcamo.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_svdcamo_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_svdcamo_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_svd_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_svd_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_tractor.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_tractor.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_tractor_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_tractor_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_tt650.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_tt650.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_tt650_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_tt650_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_uaz.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_uaz.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_uaz_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_uaz_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_uh1.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_uh1.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_uh1h_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_uh1h_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_uh1y_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_uh1y_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_ural.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_ural.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_ural_c.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_ural_c.pbo.JSRS15_V2.bisign
@KRAYZ_CBA+JSRS\addons\jsrs_vehicle_noises.pbo
@KRAYZ_CBA+JSRS\addons\jsrs_vehicle_noises.pbo.JSRS15_V2.bisign
) do %md5% %%f >> "%workingpath%\krayzlogfile.txt"
exit